import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="p-8 bg-main flex w-full justify-center min-h-screen">
          <div className="fixed z-10">
            <Navbar />
          </div>
          <div className="mt-24 z-0 block">{children}</div>
        </main>
      </body>
    </html>
  );
}
